tasks:
  - init: |
      cp -n .env-example .env
      python -m venv venv
      source venv/bin/activate
      pip install -U -r requirements.txt
    command: |
      source venv/bin/activate
      python main.py

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8090
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - oderwat.indent-rainbow
    - usernamehw.errorlens
    - eamodio.gitlens