tasks:
  - init: |
      cp -n .env-example .env
      python -m venv venv
      source venv/bin/activate
      pip install -U poetry
      pip install -r requirements.txt
      mkdir ./ffmpeg_temp
      curl https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz -o ./ffmpeg_temp/ffmpeg.tar.xz
      tar -xf ./ffmpeg_temp/ffmpeg.tar.xz --strip-components 1 -C ./ffmpeg_temp
      mv ./ffmpeg_temp/ffmpeg ./venv/bin/ffmpeg
      rm -rf ./ffmpeg_temp

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 8090
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - oderwat.indent-rainbow
    - usernamehw.errorlens
    - eamodio.gitlens