[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["xRitsu <https://github.com/zRitsu>"]
description = ""
name = "py-music-bot-disnake"
version = "0.1.0"
