[tool.poetry]
name = "Disnake-LL-MusicBot"
version = "0.1.0"
description = ""
authors = ["xRitsu <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10.2"
disnake = "2.3.0"
wavelink = {git = "https://github.com/zRitsu/Wavelink.git", rev = "b7921d7fe3defb676d0a228994647f66a3216210"}
python-dotenv = "^0.19.2"
spotipy = "^2.19.0"
requests = "^2.27.1"
humanize = "^3.13.1"
tornado = "^6.1"
motor = "^2.5.1"
dnspython = "^2.2.0"
flask = "^2.0.2"
fake-useragent = "^0.1.11"
disnake-jishaku = "^2.6.5"
psutil = "^5.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
