services:
  # A Ruby web service
  - type: web
    name: disnake_music
    env: python
    branch: experimental/render-deploy
    plan: free
    repo: https://github.com/zRitsu/disnake-LL-music-bot.git
    buildCommand: pip3 install -r requirements.txt --no-cache-dir
    startCommand: python3 main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DEFAULT_PREFIX
        value: !!!
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: MONGO
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6
    autoDeploy: false # optional
